from mcfg_parser import AgendaBasedParser, MultipleContextFreeGrammar

g = MultipleContextFreeGrammar.from_strings(
    rules=[
        "S(uv) -> NP(u) VP(v)",
        "S(uv) -> NPwh(u) VP(v)",
        "S(uv) -> Aux(u) Sinv(v)",
        "S(vuw) -> Aux(u) Swhmain(v, w)",
        "S(uvw) -> NPdisloc(u, v) VP(w)",
        "S(uwv) -> NPwhdisloc(u, v) VP(w)",
        "Sbar(uv) -> C(u) S(v)",
        "Sbarwh(v, uw) -> C(u) Swhemb(v, w)",
        "Sbarwh(u, v) -> NPwh(u) VP(v)",
        "Swhmain(v, uw) -> NP(u) VPwhmain(v, w)",
        "Swhmain(w, uxv) -> NPdisloc(u, v) VPwhmain(w, x)",
        "Swhemb(v, uw) -> NP(u) VPwhemb(v, w)",
        "Swhemb(w, uxv) -> NPdisloc(u, v) VPwhemb(w, x)",
        "Src(v, uw) -> NP(u) VPrc(v, w)",
        "Src(w, uxv) -> NPdisloc(u, v) VPrc(w, x)",
        "Src(u, v) -> N(u) VP(v)",
        "Swhrc(u, v) -> Nwh(u) VP(v)",
        "Swhrc(v, uw) -> NP(u) VPwhrc(v, w)",
        "Sbarwhrc(v, uw) -> C(u) Swhrc(v, w)",
        "Sinv(uv) -> NP(u) VPbare(v)",
        "VP(uv) -> Vpres(u) NP(v)",
        "VP(uv) -> Vpres(u) Sbar(v)",
        "VPbare(uv) -> Vroot(u) NP(v)",
        "VPwhmain(u, v) -> NPwh(u) Vroot(v)",
        "VPwhmain(u, v) -> Nwh(u) Vroot(v)",
        "VPwhmain(u, wv) -> NPwhdisloc(u, v) Vroot(w)",
        "VPwhmain(v, uw) -> Vroot(u) Sbarwh(v, w)",
        "VPwhemb(u, v) -> NPwh(u) Vpres(v)",
        "VPwhemb(u, wv) -> NPwhdisloc(u, v) Vpres(w)",
        "VPwhemb(v, uw) -> Vpres(u) Sbarwh(v, w)",
        "VPwhemb(u, v) -> Nwh(u) Vpres(v)",
        "VPrc(u, v) -> N(u) Vpres(v)",
        "VPrc(v, uw) -> Vpres(u) Nrc(v, w)",
        "VPwhrc(u, v) -> Nwh(u) Vpres(v)",
        "VPwhrc(v, uw) -> Vpres(u) Sbarwhrc(v, w)",
        "NP(uv) -> D(u) N(v)",
        "NP(uvw) -> D(u) Nrc(v, w)",
        "NPdisloc(uv, w) -> D(u) Nrc(v, w)",
        "NPwh(uv) -> Dwh(u) N(v)",
        "NPwh(uvw) -> Dwh(u) Nrc(v, w)",
        "NPwhdisloc(uv, w) -> Dwh(u) Nrc(v, w)",
        "Nrc(v, uw) -> C(u) Src(v, w)",
        "Nrc(u, vw) -> N(u) Swhrc(v, w)",
        "Nrc(u, vwx) -> Nrc(u, v) Swhrc(w, x)",
        "N(uv) -> N(u) N(v)",
        "PP(uv) -> P(u) NP(v)",
        "NP(uv) -> NP(u) PP(v)",
        "VP(uv) -> VP(u) PP(v)",
        "Nwh(what)",
        "Dwh(which)",
        "Nwh(who)",
        "D(the)",
        "D(a)",
        "N(greyhound)",
        "N(human)",
        "N(saw)",
        "N(salmon)",
        "Vpres(sees)",
        "Vpres(saw)",
        "Vroot(see)",
        "Vpres(believes)",
        "Vroot(believe)",
        "Aux(does)",
        "Aux(did)",
        "C(that)",
        "P(with)",
    ],
    parser_class=AgendaBasedParser,
    start_symbol="S",
)


trees = g.parse("the human saw the greyhound that saw the human with a salmon")
if trees:
    for t in trees:
        print(repr(t))
